name: TagBot

on:
  issue_comment:
    types:
      - created

jobs:
  TagBot:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '@TagBot tag')
    runs-on: ubuntu-latest

    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
